### ISSUE TITLE
`Walter.glb` needs certain fixes to work properly

### ISSUE THREAD

**Issue by gv-sh** [gv-sh/methlab-3js#4]
**Problem 1:** It's size is not in proportion to the scene model. It is approximately 80-90 times smaller than the sample model (Soldier) that was being used until now. 
Suggested solution: Increase the size of the model by 85 times and re-export it. If not, I can manually resize the model in the program. 

**Problem 2:** The walking animation is not smooth. It feels like some frames are missing.
Suggested solution: If this does not seem like a problem. We can skip this one. You can preview the file at https://gltf-viewer.donmccurdy.com

**Problem 3:** The model's default rotation is not correct for the scene. It needs to be rotated by 180 degrees in y-axis. While this can be fixed through the code by manually rotating the model, however (most-likely) due to certain validation warnings, this model is not rotating in y-axis. It has to do something with parent and local transformation setting in the model meshes.

![Screenshot 2023-10-17 at 7 23 44 PM](https://github.com/gv-sh/methlab-3js/assets/108992402/1915decd-e279-4b80-9959-c7e5f212c81f)

Suggested solution: The model+animation needs to be rotated by 180 degress by y-axis and then needs be re-exported.

**Problem 4:** The model has significant number of triangles, it is appearing to make the fps slow. 
Suggested solution: Decimate the model. While the size is okay, the number of triangles is not.

**Comment by Malayvasa** [comment]
Have addressed Problem 1, Problem 4 (Now down to 20k triangles).

Problem 2 can be ignored for now.

For Problem 3 we have rotated it by 180 degrees in y-axis but that is causing the model to be flipped in the viewer not sure if that is what we needed in the first place.

Model file sent to you via email.
