### ISSUE TITLE
Character movement needs improvements

### ISSUE THREAD

**Issue by Malayvasa** [gv-sh/methlab-3js#5]
While we are getting decent FPS, the movement still feels stuttery.
Refer to this link as an example of the kind of movement we'd like.
https://jblaha.art/sketchbook/0.4/

**Comment by gv-sh** [comment]
- [x] Allow simultaneous controls (moving forward in conjunction with left/right) → Fixed in #7 
- [ ] Added ease-in/out via accelleration/de-accelleration to make the movement more fluid.
- [ ] Add additional animation states for turning left, right and back to avoid model being rotated in static.

**Comment by gv-sh** [comment]
Same comment as https://github.com/gv-sh/methlab-3js/issues/18#issuecomment-1773308040
