### ISSUE TITLE
Add a loading state/screen

### ISSUE THREAD

**Issue by Malayvasa** [gv-sh/methlab-3js#6]
In the current pipeline, the hdri loads first, then the character and then the scene. Let's display all of it together once loaded.

**Comment by gv-sh** [comment]
Comment for self: Implement asynchronous loading for scene initiation.

**Comment by gv-sh** [comment]
In view of time, I have implemented a time out of 3 seconds which gives adequate time to build the scene in the background. I will map this to reflect actual loading of the scene components.
